import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Toaster } from './components/ui/sonner';
import Footer from './components/ui/footer';
import AuthProvider from './_providers/auth';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning className='dark'>
      <body suppressHydrationWarning className={inter.className}>
        <AuthProvider>
        {children}
        <Toaster />
        <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}